name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build project
        run: ./gradlew build -PdisablePreDex

      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(./getVersion.sh)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: "AssetExtractor-Android v${{ steps.get_version.outputs.version }} - ${{ github.event.commits[0].message }} - ${{ github.ref }}"
          draft: true
          prerelease: false

      - name: Upload Release aar
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./assetextractor/build/outputs/aar/assetextractor-android-release.aar
          asset_name: assetextractor-android-release.aar
          asset_content_type: application/zip

      - name: Upload Debug aar
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./assetextractor/build/outputs/aar/assetextractor-android-debug.aar
          asset_name: assetextractor-android-debug.aar
          asset_content_type: application/zip

      - name: Generate javadoc
        run: ./gradlew assetextractor:javadocJar

      - name: Upload javadoc.jar
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./assetextractor/build/libs/assetextractor-android-${{steps.get_version.outputs.version}}-javadoc.jar
          asset_name: assetextractor-android-${{steps.get_version.outputs.version}}-javadoc.jar
          asset_content_type: application/zip

      - name: Jar the sources
        run: ./gradlew sourceJar

      - name: Upload sources.jar
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./assetextractor/build/libs/assetextractor-android-${{steps.get_version.outputs.version}}-sources.jar
          asset_name: assetextractor-android-${{steps.get_version.outputs.version}}-sources.jar
          asset_content_type: application/zip
