name: privilegedBuild
on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/manualVersionIncrement*.yml'
      - '.github/workflows/unprivilegedBuild.yml'

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    environment: BuildWithDeployToSonatype
    outputs:
      STAGING_REPO_URL: ${{ steps.sonatype.outputs.stagingRepoUrl }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3

      - run: ./gradlew assembleRelease

      - name: 'Publish to Sonatype'
        run: ./gradlew publishToSonatype closeSonatypeStagingRepository | tee publishToSonatype.log
        # bash has pipefail on by default, which is needed for tee to fail, if gradle fails
        shell: bash
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASS: ${{ secrets.SIGNING_PASS }}

      - name: 'Parse Sonatype repository'
        id: sonatype
        # publishToSonatype.log contains a line looking like this:
        # Created staging repository 'comviliussutkus89-1055' at https://oss.sonatype.org/service/local/repositories/comviliussutkus89-1055/content/
        run: perl -ne 'print "::set-output name=stagingRepoUrl::$2\n::warning ::$1\n" if /^(Created staging repository .+ at (.+))$/' < publishToSonatype.log

      - run: ./gradlew publishToMavenLocal
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASS: ${{ secrets.SIGNING_PASS }}

      - run: tar -cvf maven-local.tar ~/.m2

      - uses: actions/upload-artifact@v3
        with:
          name: maven-local
          path: maven-local.tar

  staging:
    environment: Staging
    needs: build
    # Only macos VMs are available with exposed CPU extensions to run hardware accelerated emulator
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        api-level: [21, 29]
        arch: [x86, x86_64]
        target: [default]
        include:
          - api-level: 15
            arch: x86
            target: default
          - api-level: 34
            arch: x86_64
            target: google_apis
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3

      - run: ./ci-scripts/prepareLibraryTestsForStagingRepository assetextractor --output=build/lib-staging --repository=${{ needs.build.outputs.STAGING_REPO_URL }}

      - run: ./gradlew assemble
        working-directory: build/lib-staging

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          target: ${{ matrix.target }}
          script: ./gradlew connectedCheck
          working-directory: build/lib-staging

  releaseSonatype:
    environment: ReleaseSonatype
    # Needs to depend on build too, to obtain STAGING_REPO_URL
    needs: [build, staging]
    runs-on: ubuntu-22.04
    outputs:
      ARTIFACTS: ${{ steps.promote.outputs.artifacts }}
    steps:
      - uses: ViliusSutkus89/promote-Nexus-repository-to-MavenCentral@v1
        id: promote
        with:
          repositoryURL: ${{ needs.build.outputs.STAGING_REPO_URL }}
          sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}

  releaseGitHub:
    environment: ReleaseGitHub
    needs: releaseSonatype
    permissions:
      # Needed to make a version increment commit, maybe GitHub release too.
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          # A branch is required for post release version increment commit
          ref: ${{ github.event.ref }}

      - uses: actions/download-artifact@v3
        with:
          name: maven-local

      - run: ./ci-scripts/incrementVersion --release --patch
        id: version

      - uses: ViliusSutkus89/WaitForURLsToBeAvailable@v1
        with:
          URLs: ${{ needs.releaseSonatype.outputs.ARTIFACTS }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.version.outputs.releasedVersion }}"
          name: "${{ github.event.repository.name }} v${{ steps.version.outputs.releasedVersion }}"
          artifacts: "maven-local.tar"
          bodyFile: "UpcomingReleaseNotes.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Post release version increment to ${{ steps.version.outputs.unreleasedVersion }} (from ${{ steps.version.outputs.releasedVersion }})"
          file_pattern: ${{ steps.version.outputs.files }}

      - run: echo -n > UpcomingReleaseNotes.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Post release truncation of UpcomingReleaseNotes.md"
          file_pattern: UpcomingReleaseNotes.md
