name: unprivilegedBuild
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/manualVersionIncrement*.yml'
      - '.github/workflows/privilegedBuild.yml'

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    environment: BuildUnprivileged
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3

      - run: ./gradlew assembleRelease

      - run: ./gradlew publishToMavenLocal

      - uses: actions/upload-artifact@v3
        with:
          name: maven-local
          path: ~/.m2

  staging:
    needs: build
    environment: BuildUnprivileged
    # Only macos VMs are available with exposed CPU extensions to run hardware accelerated emulator
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        api-level: [21, 29]
        arch: [x86, x86_64]
        target: [default]
        include:
          - api-level: 15
            arch: x86
            target: default
          - api-level: 34
            arch: x86_64
            target: google_apis
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3

      - uses: actions/download-artifact@v3
        with:
          name: maven-local
          path: ~/.m2

      - name: Prepare library to run instrumented tests on staging library
        run: ./ci-scripts/prepareLibraryTestsForStagingRepository assetextractor --output=build/lib-staging --repository=mavenLocal

      - run: ./gradlew assemble
        working-directory: build/lib-staging

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          target: ${{ matrix.target }}
          script: ./gradlew connectedCheck
          working-directory: build/lib-staging
